on:
  schedule:
    - cron: "0 0/4 * * *"
  push:
    paths:
      - .github/workflows/nvd-cache.yml

permissions:
  contents: write

env:
  NVD_API_KEY: f3868dd7-4252-4586-b61c-bf9214591c86
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cache NVD data
        uses: actions/cache@v4
        with:
          path: nvd
          key: nvd

      - name: Setup dependency-check
        run: |
          curl -sSL https://github.com/jeremylong/DependencyCheck/releases/download/v12.0.2/dependency-check-12.0.2-release.zip -o dependency-check.zip
          unzip -q dependency-check.zip -d ~

      - name: Download NVD CVE with the API
        run: ~/dependency-check/bin/dependency-check.sh dependency-check --nvdApiKey="$NVD_API_KEY" --updateonly --data nvd

      - name: Create NVD Archive
        run: tar -czf nvd.tar.gz nvd

      - name: Create NVD Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ github.token }}
          tag_name: nvd-latest
          prerelease: false
          files: nvd.tar.gz
